### PR TITLE
Homework 12. Part 01. Add Roles and environments for ansible playbooks.

### PR DESCRIPTION
**Pull request by iskinn**
Homework 12. Part 01. Add Roles and environments for ansible playbooks.

Прошу продиагностировать ошибку при выполнении задания со звездочкой. Версия 2.4.0.

При накатке плейбука с ролью nginx - выходит ошибка. Значение для шаблона не подставляется из переменных файла defaults/main.yml. Перепробовал разные варианты, прописывал в разных местах: в самом плейбуке, в defaults, в vars. Но пока что просвета не вижу. Сейчас прописаны настройки дефолтовые для конфигов сайтов для nginx. Если заработает - поставлю нужные.

Ошибка:

ansible-playbook app_nginx.yml --check
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 
'include_tasks' for dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation 
details page may explain more about this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Configure puma aplication on app hosts] ***************************************************************************

TASK [Gathering Facts] **************************************************************************************************
ok: [appserver]

TASK [mediapeers.nginx : Ensure APT official nginx key] *****************************************************************
ok: [appserver]

TASK [mediapeers.nginx : Ensure APT official nginx repository] **********************************************************
ok: [appserver]

TASK [mediapeers.nginx : Install the nginx packages] ********************************************************************
ok: [appserver] => (item=[u'python-selinux', u'nginx'])

TASK [mediapeers.nginx : Disable the default site] **********************************************************************
ok: [appserver]

TASK [mediapeers.nginx : Remove the default configuration] **************************************************************
ok: [appserver]

TASK [mediapeers.nginx : Find enabled sites] ****************************************************************************
skipping: [appserver]

TASK [mediapeers.nginx : Disable unmanaged sites] ***********************************************************************
skipping: [appserver] => (item=enabled_sites.stdout_lines) 

TASK [mediapeers.nginx : Find config files] *****************************************************************************
skipping: [appserver]

TASK [mediapeers.nginx : Remove unmanaged config files] *****************************************************************
skipping: [appserver] => (item=config_files.stdout_lines) 

TASK [mediapeers.nginx : Remove unwanted sites] *************************************************************************
ok: [appserver] => (item=[u'sites-enabled', u'nginx_remove_sites'])
ok: [appserver] => (item=[u'sites-available', u'nginx_remove_sites'])

TASK [mediapeers.nginx : Remove unwanted conf] **************************************************************************
ok: [appserver] => (item=nginx_remove_configs)

TASK [mediapeers.nginx : Remove unwanted auth_basic_files] **************************************************************
ok: [appserver] => (item=nginx_remove_auth_basic_files)

TASK [mediapeers.nginx : Create the directories for site specific configurations] ***************************************
ok: [appserver] => (item=sites-available)
ok: [appserver] => (item=sites-enabled)
ok: [appserver] => (item=auth_basic)
ok: [appserver] => (item=conf.d)

TASK [mediapeers.nginx : Ensure log directory exist] ********************************************************************
ok: [appserver]

TASK [mediapeers.nginx : Copy the nginx configuration file] *************************************************************
changed: [appserver]

TASK [mediapeers.nginx : Create the configurations for sites] ***********************************************************
failed: [appserver] (item=nginx_sites.keys()) => {"changed": false, "failed": true, "item": "nginx_sites.keys()", "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute u'nginx_sites.keys()'"}

RUNNING HANDLER [mediapeers.nginx : restart nginx] **********************************************************************
	to retry, use: --limit @/Users/anton/infra/ansible/app_nginx.retry

PLAY RECAP **************************************************************************************************************
appserver                  : ok=12   changed=1    unreachable=0    failed=1

### CODE REVIEW

**Comment by Artemmkin** [comment]
Привет! Ошибка у меня воспроизводится, я сейчас еще посмотрю, в чем конкретно проблема, но меня уже настораживает, что в [списке](https://galaxy.ansible.com/mediapeers/nginx/) поддерживаемых платформ нет `ubuntu 16.04`

**Comment by iskinn** [comment]
Кажется я неправильную роль использовал. Переделаю. Позже извещу об изменениях.

**Comment by Artemmkin** [comment]
роль эту точно не нужно использовать, она проблемная, использует кучу депрекейтнутых вещей и просто валится в некоторых местах из-за подобных ошибок. 
По этому заданию: править роль не нужно самому. А то я понять не могу, где ошибка твоя, а где ошибка роли. Нужно найти рабочую роль, которую можно использовать без изменений. Пример такой роли был дан в дз.

**Comment by iskinn** [comment]
Переделал задание с ролью в другой ветке ansible-4

**Pull request closed without merging**
